# automatically generated by the FlatBuffers compiler, do not modify

# namespace: bpio

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponsePacket(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponsePacket()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponsePacket(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResponsePacket
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponsePacket
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ResponsePacket
    def PacketType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ResponsePacket
    def Packet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ResponsePacketStart(builder):
    builder.StartObject(3)

def Start(builder):
    ResponsePacketStart(builder)

def ResponsePacketAddSequence(builder, sequence):
    builder.PrependUint16Slot(0, sequence, 0)

def AddSequence(builder, sequence):
    ResponsePacketAddSequence(builder, sequence)

def ResponsePacketAddPacketType(builder, packetType):
    builder.PrependUint8Slot(1, packetType, 0)

def AddPacketType(builder, packetType):
    ResponsePacketAddPacketType(builder, packetType)

def ResponsePacketAddPacket(builder, packet):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(packet), 0)

def AddPacket(builder, packet):
    ResponsePacketAddPacket(builder, packet)

def ResponsePacketEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResponsePacketEnd(builder)
